trigger:
- main
- feature/*
   
pool:
  name: 'azure-devops-self-host'

variables:
  imageName: 'dotnet'
  DOCKER_BUILDKIT: 1

stages:
  - stage: QA
    displayName: Quality Tests

    jobs:
    - job: SonarQube

      steps:
      - task: SonarCloudPrepare@1
        displayName: Prepare Analysis Configuration task
        inputs:
          SonarCloud: 'SonarCloud'
          organization: 'azuredevopsleandro'
          scannerMode: 'MSBuild'
          projectKey: 'azuredevopsleandro_dotNet-Pipeline'
          projectName: 'dotNet Pipeline'

      - task: SonarCloudAnalyze@1
        displayName: Run Code Analysis

      - task: SonarCloudPublish@1
        displayName: Publish Quality Gate Result
        inputs:
          pollingTimeoutSec: '300'
