trigger:
- main
- feature/*
   
pool:
  name: self

variables:
  imageName: 'dotnet'
  DOCKER_BUILDKIT: 1

stages:
  - stage: QA
    displayName: Quality Tests

    jobs:
    - job: SonarQube

      steps:
      - task: SonarCloudPrepare@1
        displayName: Prepare Analysis Configuration task
        inputs:
          SonarCloud: 'SonarCloud'
          organization: 'azuredevopsleandro'
          scannerMode: 'CLI'
          configMode: 'manual'
          cliProjectKey: 'azuredevopsleandro_dotNet-Pipeline'
          cliProjectName: 'dotNet Pipeline'
          cliSources: '.'

      - task: SonarCloudAnalyze@1
        displayName: Run Code Analysis

      - task: SonarCloudPublish@1
        displayName: Publish Quality Gate Result
        inputs:
          pollingTimeoutSec: '300'
