trigger:
- main
- feature/*
   
pool:
  vmImage: 'ubuntu-latest'

variables:
  imageName: 'dot-net'
  DOCKER_BUILDKIT: 1
    
steps:
- task: Docker@2
  displayName: Build an image
  inputs:
    repository: $(imageName)
    command: build
    Dockerfile: Dockerfile